### ISSUE TITLE
not reading follower count 

### ISSUE THREAD

**Issue by saiyanloki** [maael/giveaway-o-tron#7]
![image](https://github.com/maael/giveaway-o-tron/assets/146039321/4165422b-586b-4c4a-844a-3d0fc631c991)
not reading follower count after updating. only way to use is to turn followers only off 
![image](https://github.com/maael/giveaway-o-tron/assets/146039321/176b8054-acb8-4e10-af04-6bb192ca2483)
it shows a green check next to it but the bar stays gray

**Comment by maael** [comment]
:wave: Hey there - this should be fixed in the latest copy of the app now, version `v3.2.4` onwards. Sorry about that, due to a Twitch API change they were being collected, but not saved properly.

You might have to update the app, and then close and re-open it for the followers to register.

Let me know if that seems to have fixed it for you!

**Comment by maael** [comment]
I'm going to go ahead and close this, as it should be fixed.

There's also a web version of the app now too, available at: https://giveaway-o-tron.mael.tech/app.
